name: CI for Node.js App

on:
  push:
    branches: [main] # Specify the branch that will trigger the workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
      
    # Continue to the second job if the first job completes successfully
    if: success()

  build_and_publish:
    runs-on: ubuntu-latest
    needs: build_and_test # Depend on the first job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-repository-name:latest .
          docker push your-dockerhub-username/your-repository-name:latest